version: '2'
services:
  mongodb:
    image: "mongo:latest"
    ports:
      - "27017:27017"

  backend:
    build: ./backend
    ports:
      - "3000:3000"
    volumes:
      - ./backend:/backend

  app:
    build: ./client
    ports: 
        - "80:4200"
