version: "3"
services:
  mongodbwi:
    image: "mongo:latest"
    ports:
      - "27017:27017"
    container_name: mongodbwi

  backendwi:
    build: ./backend
    ports:
      - "3000:3000"
    links:
      - mongodbwi
    container_name: backendwi

  clientwi:
    build: ./client
    ports: 
        - "80:4200"
    container_name: clientwi
